"use client";

import { useState, useCallback } from "react";
import {
  Sparkles, Download, Code2, Eye, Save, Trash2, RefreshCw,
  ChevronDown, Loader2, CheckCircle, AlertCircle
} from "lucide-react";
import { generateWebsite } from "@/lib/generator";
import { saveProject, getProjects, deleteProject } from "@/lib/storage";
import { Project, Template } from "@/types";
import { cn } from "@/lib/utils";
import JSZip from "jszip";
import { saveAs } from "file-saver";

const EXAMPLE_PROMPTS = [
  "Create a restaurant website for Spice Garden with menu, gallery, and contact page",
  "Build a photography portfolio website for John Smith with dark theme",
  "Make a modern e-commerce shop for fashion clothing and accessories",
  "Create a corporate business website for TechSolutions with services and testimonials",
  "Design a food blog website with recipe categories and newsletter signup",
];

const TEMPLATES: { value: Template; label: string; emoji: string }[] = [
  { value: "business", label: "Business", emoji: "💼" },
  { value: "portfolio", label: "Portfolio", emoji: "🎨" },
  { value: "restaurant", label: "Restaurant", emoji: "🍽️" },
  { value: "shop", label: "Shop", emoji: "🛒" },
  { value: "blog", label: "Blog", emoji: "📰" },
  { value: "news", label: "News", emoji: "📡" },
];

type PanelMode = "preview" | "code";

export function WebsiteBuilder() {
  const [prompt, setPrompt] = useState("");
  const [activeTemplate, setActiveTemplate] = useState<Template>("business");
  const [generatedHTML, setGeneratedHTML] = useState("");
  const [editableHTML, setEditableHTML] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [panelMode, setPanelMode] = useState<PanelMode>("preview");
  const [savedProjects, setSavedProjects] = useState<Project[]>([]);
  const [projectsOpen, setProjectsOpen] = useState(false);
  const [notification, setNotification] = useState<{ type: "success" | "error"; msg: string } | null>(null);
  const [currentProjectName, setCurrentProjectName] = useState("");

  const showNotification = (type: "success" | "error", msg: string) => {
    setNotification({ type, msg });
    setTimeout(() => setNotification(null), 3000);
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      showNotification("error", "Please enter a prompt first");
      return;
    }
    setIsGenerating(true);
    // Simulate AI processing delay for UX
    await new Promise((r) => setTimeout(r, 1200 + Math.random() * 800));
    const { html, template } = generateWebsite(prompt);
    setGeneratedHTML(html);
    setEditableHTML(html);
    setActiveTemplate(template);
    setIsGenerating(false);
    showNotification("success", "Website generated successfully!");
  };

  const handleCodeChange = (val: string) => {
    setEditableHTML(val);
  };

  const handlePreviewRefresh = () => {
    setGeneratedHTML(editableHTML);
  };

  const handleSave = () => {
    if (!editableHTML) {
      showNotification("error", "Generate a website first before saving");
      return;
    }
    const name = currentProjectName || `Project – ${new Date().toLocaleDateString("en-IN")}`;
    saveProject({ name, prompt, template: activeTemplate, html: editableHTML });
    showNotification("success", "Project saved locally!");
    setSavedProjects(getProjects());
  };

  const handleDownload = async () => {
    if (!editableHTML) {
      showNotification("error", "Generate a website first");
      return;
    }
    const zip = new JSZip();
    zip.file("index.html", editableHTML);
    zip.file("README.txt", `Website generated by WebCraftAI\nPrompt: ${prompt}\nDate: ${new Date().toLocaleDateString("en-IN")}\n\nTo use this website:\n1. Open index.html in a browser\n2. Upload files to any web host\n3. Enjoy your new website!\n\nFor customization help, contact us on WhatsApp: +91 98765 43210`);
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `website-${Date.now()}.zip`);
    showNotification("success", "Website downloaded as ZIP!");
  };

  const handleLoadProject = (project: Project) => {
    setEditableHTML(project.html);
    setGeneratedHTML(project.html);
    setPrompt(project.prompt);
    setActiveTemplate(project.template);
    setCurrentProjectName(project.name);
    setProjectsOpen(false);
    showNotification("success", `Loaded: ${project.name}`);
  };

  const handleDeleteProject = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    deleteProject(id);
    setSavedProjects(getProjects());
  };

  const openProjects = () => {
    setSavedProjects(getProjects());
    setProjectsOpen(!projectsOpen);
  };

  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 py-8 lg:py-12">
      {/* Notification */}
      {notification && (
        <div className={cn(
          "fixed top-20 right-4 z-50 flex items-center gap-2 px-4 py-3 rounded-xl shadow-lg text-sm font-semibold animate-slide-up",
          notification.type === "success"
            ? "bg-green-50 text-green-800 border border-green-200 dark:bg-green-950 dark:text-green-300 dark:border-green-800"
            : "bg-red-50 text-red-800 border border-red-200 dark:bg-red-950 dark:text-red-300 dark:border-red-800"
        )}>
          {notification.type === "success" ? <CheckCircle className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}
          {notification.msg}
        </div>
      )}

      {/* Prompt Section */}
      <div className="card p-6 mb-6">
        <div className="flex items-center gap-3 mb-5">
          <div className="w-10 h-10 bg-gradient-to-br from-brand-500 to-accent-500 rounded-xl flex items-center justify-center shadow-md">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-extrabold text-gray-900 dark:text-white">AI Website Generator</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">Describe your website and we'll build it instantly</p>
          </div>
        </div>

        {/* Template pills */}
        <div className="flex gap-2 flex-wrap mb-4">
          {TEMPLATES.map((t) => (
            <button
              key={t.value}
              onClick={() => setActiveTemplate(t.value)}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all",
                activeTemplate === t.value
                  ? "bg-brand-600 text-white shadow-sm"
                  : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
              )}
            >
              {t.emoji} {t.label}
            </button>
          ))}
        </div>

        {/* Prompt input */}
        <div className="relative mb-4">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) handleGenerate();
            }}
            placeholder="Describe your website… e.g. 'Create a restaurant website for Spice Garden with a menu section, photo gallery, and contact form'"
            rows={3}
            className="input resize-none text-sm pr-32"
          />
          <div className="absolute bottom-3 right-3 text-xs text-gray-400">
            ⌘ + Enter to generate
          </div>
        </div>

        {/* Example prompts */}
        <div className="flex gap-2 flex-wrap mb-5">
          {EXAMPLE_PROMPTS.slice(0, 3).map((ex) => (
            <button
              key={ex}
              onClick={() => setPrompt(ex)}
              className="text-xs px-3 py-1.5 bg-gray-50 dark:bg-gray-800/60 text-gray-600 dark:text-gray-400 border border-gray-200 dark:border-gray-700 rounded-lg hover:border-brand-400 hover:text-brand-600 dark:hover:text-brand-400 transition-all truncate max-w-xs"
            >
              {ex.slice(0, 48)}…
            </button>
          ))}
        </div>

        {/* Actions row */}
        <div className="flex flex-wrap gap-3 items-center">
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="btn-primary flex items-center gap-2 disabled:opacity-70"
          >
            {isGenerating ? (
              <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</>
            ) : (
              <><Sparkles className="w-4 h-4" /> Generate Website</>
            )}
          </button>

          <button onClick={handleSave} className="btn-secondary flex items-center gap-2">
            <Save className="w-4 h-4" /> Save
          </button>

          <button onClick={handleDownload} className="btn-secondary flex items-center gap-2">
            <Download className="w-4 h-4" /> Download ZIP
          </button>

          <div className="relative ml-auto">
            <button
              onClick={openProjects}
              className="flex items-center gap-2 text-sm font-medium text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white px-3 py-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
            >
              Saved Projects <ChevronDown className={cn("w-4 h-4 transition-transform", projectsOpen && "rotate-180")} />
            </button>
            {projectsOpen && (
              <div className="absolute right-0 top-full mt-2 w-72 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl shadow-xl z-30 overflow-hidden">
                <div className="p-3 border-b border-gray-100 dark:border-gray-800 text-xs font-bold text-gray-500 uppercase tracking-wider">
                  Saved Projects ({savedProjects.length})
                </div>
                <div className="max-h-64 overflow-y-auto">
                  {savedProjects.length === 0 ? (
                    <p className="p-4 text-sm text-gray-400 text-center">No saved projects yet</p>
                  ) : (
                    savedProjects.map((proj) => (
                      <div
                        key={proj.id}
                        onClick={() => handleLoadProject(proj)}
                        className="flex items-start justify-between gap-2 p-3 hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer border-b border-gray-50 dark:border-gray-800 last:border-0"
                      >
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-gray-900 dark:text-white truncate">{proj.name}</p>
                          <p className="text-xs text-gray-400 truncate">{proj.prompt.slice(0, 40)}…</p>
                        </div>
                        <button
                          onClick={(e) => handleDeleteProject(proj.id, e)}
                          className="p-1 text-gray-300 hover:text-red-500 transition-colors flex-shrink-0"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Builder Panels */}
      {(generatedHTML || isGenerating) && (
        <div className="card overflow-hidden">
          {/* Panel header */}
          <div className="flex items-center justify-between px-4 py-3 bg-gray-50 dark:bg-gray-900/60 border-b border-gray-200 dark:border-gray-800">
            <div className="flex gap-1">
              <button
                onClick={() => setPanelMode("preview")}
                className={cn(
                  "flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-sm font-semibold transition-all",
                  panelMode === "preview"
                    ? "bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm"
                    : "text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
                )}
              >
                <Eye className="w-4 h-4" /> Preview
              </button>
              <button
                onClick={() => setPanelMode("code")}
                className={cn(
                  "flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-sm font-semibold transition-all",
                  panelMode === "code"
                    ? "bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm"
                    : "text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
                )}
              >
                <Code2 className="w-4 h-4" /> Code Editor
              </button>
            </div>
            <div className="flex items-center gap-2">
              {panelMode === "code" && (
                <button
                  onClick={handlePreviewRefresh}
                  className="flex items-center gap-1.5 text-xs text-brand-600 dark:text-brand-400 font-semibold hover:underline"
                >
                  <RefreshCw className="w-3.5 h-3.5" /> Apply Changes
                </button>
              )}
              <button onClick={handleDownload} className="flex items-center gap-1.5 text-xs font-semibold text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-white">
                <Download className="w-3.5 h-3.5" /> Download
              </button>
            </div>
          </div>

          {/* Panel content */}
          <div className="relative" style={{ height: "680px" }}>
            {isGenerating && (
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-900 z-10">
                <div className="w-16 h-16 bg-gradient-to-br from-brand-500 to-accent-500 rounded-2xl flex items-center justify-center shadow-xl mb-5 animate-pulse-slow">
                  <Sparkles className="w-8 h-8 text-white" />
                </div>
                <p className="text-lg font-bold text-gray-900 dark:text-white mb-1">Building your website…</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Analyzing prompt and generating code</p>
                <div className="mt-6 w-64 bg-gray-200 dark:bg-gray-700 rounded-full h-1.5">
                  <div className="bg-gradient-to-r from-brand-500 to-accent-500 h-1.5 rounded-full animate-pulse" style={{ width: "75%" }} />
                </div>
              </div>
            )}

            {panelMode === "preview" && !isGenerating && (
              <iframe
                srcDoc={generatedHTML}
                title="Website Preview"
                className="w-full h-full border-0"
                sandbox="allow-scripts allow-same-origin"
              />
            )}

            {panelMode === "code" && !isGenerating && (
              <div className="h-full flex flex-col bg-gray-950">
                <div className="flex items-center gap-1.5 px-4 py-2 bg-gray-900 border-b border-gray-800">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-400" />
                  <div className="w-3 h-3 rounded-full bg-green-500" />
                  <span className="ml-3 text-xs text-gray-500 font-mono">index.html</span>
                </div>
                <textarea
                  value={editableHTML}
                  onChange={(e) => handleCodeChange(e.target.value)}
                  className="flex-1 bg-gray-950 text-green-400 font-mono text-xs p-4 resize-none outline-none leading-relaxed"
                  spellCheck={false}
                />
              </div>
            )}
          </div>
        </div>
      )}

      {/* Empty state */}
      {!generatedHTML && !isGenerating && (
        <div className="card p-12 text-center">
          <div className="w-20 h-20 bg-gradient-to-br from-brand-100 to-accent-400/20 dark:from-brand-950 dark:to-brand-900 rounded-3xl flex items-center justify-center mx-auto mb-6">
            <Sparkles className="w-10 h-10 text-brand-500" />
          </div>
          <h3 className="text-xl font-extrabold text-gray-900 dark:text-white mb-2">Your website will appear here</h3>
          <p className="text-gray-500 dark:text-gray-400 max-w-sm mx-auto mb-6">
            Enter a prompt above and click "Generate Website" to create your custom site instantly.
          </p>
          <div className="flex flex-col gap-2 max-w-sm mx-auto">
            {EXAMPLE_PROMPTS.map((ex) => (
              <button
                key={ex}
                onClick={() => setPrompt(ex)}
                className="text-sm text-left px-4 py-2.5 bg-gray-50 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700 rounded-lg hover:border-brand-400 hover:bg-brand-50 dark:hover:bg-brand-950/30 hover:text-brand-700 dark:hover:text-brand-300 transition-all text-gray-600 dark:text-gray-400"
              >
                → {ex}
              </button>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}
